import type {
  HubLine,
  HubLineInput,
  HubPublisher,
  HubPublisherInput,
  Location,
  RestockItem,
  RestockItemInput,
} from "@/lib/types";

/**
 * Ordering Hub seam. Lifecycle (spec C2–C4):
 *   draft → pending → ordered → arrived (terminal)
 * Restock (C5) never enters that lifecycle — capture → handled, done.
 *
 * Cross-module orchestration (a book-club selection creating a draft; an
 * arrival writing back to a customer order) happens in the API routes, so
 * each source stays single-purpose.
 */
export interface HubDataSource {
  listLines(): Promise<HubLine[]>;
  getLine(id: string): Promise<HubLine | null>;

  /** Stage a draft (Flow A). Lines share a draftKey and review as one card. */
  createDraft(lines: HubLineInput[], byName: string): Promise<HubLine[]>;
  /** Create-or-replace the draft line generated by a source record (used by
   *  book-club selections so re-picking updates rather than duplicates). */
  upsertSourceDraft(input: HubLineInput, byName: string): Promise<HubLine>;
  /** Inline staging edits: quantity (the single most common adjustment),
   *  publisher correction, price. */
  updateDraftLine(id: string, patch: Partial<Pick<HubLine, "quantity" | "publisherId" | "imprint" | "rrp" | "title" | "isbn">>): Promise<HubLine>;
  /** Account assignment applies to the whole draft card (C2). */
  setDraftAccount(draftKey: string, account: Location, byName: string): Promise<void>;
  /** Logged delete (C2). Never touches the originating record. */
  deleteDraft(draftKey: string, byName: string): Promise<HubLine[]>;
  /** Draft → Pending. Rejected if any line lacks an account. */
  pushDraft(draftKey: string, byName: string): Promise<HubLine[]>;

  /** Pending → Ordered for one publisher × account batch, recording method,
   *  who, when and the exact sent copy (C3). */
  markSent(
    publisherId: string,
    account: Location,
    method: "Email" | "CSV",
    byName: string,
    sentCopy: string
  ): Promise<HubLine[]>;

  /** Receive copies. A line remains ordered until its full quantity arrives. */
  receive(receipts: { lineId: string; quantity: number }[], byName: string): Promise<HubLine[]>;
  /** Compatibility shortcut: receive every outstanding copy on each line. */
  markArrived(lineIds: string[], byName: string): Promise<HubLine[]>;

  // --- Publishers reference data (C6) — staff-maintained, never hardcoded ---
  listPublishers(): Promise<HubPublisher[]>;
  createPublisher(input: HubPublisherInput): Promise<HubPublisher>;
  updatePublisher(id: string, input: Partial<HubPublisherInput>): Promise<HubPublisher>;

  // --- Restock (C5) — decision-support only ---
  listRestock(): Promise<RestockItem[]>;
  addRestock(input: RestockItemInput): Promise<RestockItem>;
  /** "Mark as handled" — the order itself is placed in Batchline. */
  handleRestock(id: string, byName: string): Promise<RestockItem>;
}
