import type {
  AuditEntry,
  HubLine,
  HubLineInput,
  HubPublisher,
  HubPublisherInput,
  RestockItem,
  RestockItemInput,
} from "@/lib/types";
import type { HubDataSource } from "./hub-source";
import { clubsMockStore } from "./clubs-mock";
import { currentMonthKey } from "@/lib/clubs";

// In-memory Ordering Hub store — same rules as clubs-mock. Draft lines for
// book-club picks mirror the selections clubs-mock seeded (deterministic
// HL-bc-<clubId> / sel_<clubId>_<month> ids keep the two in step).

const PUBLISHER_SEED: HubPublisher[] = [
  {
    id: "pubPRH", name: "Penguin Random House", repName: "Marcus Reed", repEmail: "m.reed@penguinrandomhouse.co.uk",
    accountNumbers: { "Simply Books": "PRH-SB-4471", "Prologue": "PRH-PR-8890" },
    imprints: ["Fig Tree", "Hamish Hamilton", "Viking", "Vintage", "Jonathan Cape"],
    rates: { restock: 48, bookclub: 50, events: 52, schools: 49 }, accountOverrides: {},
  },
  {
    id: "pubFaber", name: "Faber & Faber", repName: "Ellie Doran", repEmail: "e.doran@faber.co.uk",
    // Prologue account number deliberately missing — demonstrates the C6
    // "sending blocked with a clear error" path in dev.
    accountNumbers: { "Simply Books": "FAB-00921", "Prologue": "" },
    imprints: ["Faber", "Faber Editions"],
    rates: { restock: 50, bookclub: 52, events: 55, schools: 50 }, accountOverrides: {},
  },
  {
    id: "pubBloomsbury", name: "Bloomsbury", repName: "Sana Iqbal", repEmail: "s.iqbal@bloomsbury.com",
    accountNumbers: { "Simply Books": "BLM-SB-1130", "Prologue": "BLM-PR-1131" },
    imprints: ["Bloomsbury Circus", "Raven", "Head of Zeus"],
    rates: { restock: 47, bookclub: 49, events: 53, schools: 48 }, accountOverrides: {},
  },
  {
    id: "pubPanMac", name: "Pan Macmillan", repName: "Tom Fletcher", repEmail: "t.fletcher@panmacmillan.com",
    accountNumbers: { "Simply Books": "PM-SB-7742", "Prologue": "PM-PR-7743" },
    imprints: ["Picador", "Mantle", "Bello"],
    rates: { restock: 46, bookclub: 50, events: 54, schools: 48 },
    // The rare per-account exception (C6) — visually flagged in Publishers.
    accountOverrides: { Prologue: { restock: 50 } },
  },
  {
    id: "pubHarper", name: "HarperCollins", repName: "Grace Owusu", repEmail: "g.owusu@harpercollins.co.uk",
    accountNumbers: { "Simply Books": "HC-SB-3308", "Prologue": "HC-PR-3309" },
    imprints: ["Fourth Estate", "Borough Press", "Voyager"],
    rates: { restock: 49, bookclub: 51, events: 53, schools: 50 }, accountOverrides: {},
  },
  {
    id: "pubCanongate", name: "Canongate", repName: "Fraser Bell", repEmail: "f.bell@canongate.co.uk",
    accountNumbers: { "Simply Books": "CAN-2201", "Prologue": "CAN-2202" },
    imprints: ["Canongate", "Severin"],
    rates: { restock: 48, bookclub: 50, events: 52, schools: 49 }, accountOverrides: {},
  },
];

interface Store {
  lines: HubLine[];
  publishers: HubPublisher[];
  restock: RestockItem[];
}

const daysAgoIso = (d: number) => new Date(Date.now() - d * 864e5).toISOString();

function seed(): Store {
  const clubs = clubsMockStore();
  const month = currentMonthKey();
  const lines: HubLine[] = [];

  const base = { receivedQuantity: 0, sentAt: null, sentBy: "", sentMethod: "" as const, sentCopy: "", arrivedAt: null, log: [] as AuditEntry[] };

  // Drafts auto-generated by this month's book-club selections (Flow A).
  for (const sel of clubs.selections) {
    if (sel.month !== month || !sel.hubLineId) continue;
    const club = clubs.clubs.find((c) => c.id === sel.clubId)!;
    lines.push({
      id: sel.hubLineId,
      title: sel.title, isbn: sel.isbn, quantity: sel.quantity,
      publisherId: sel.publisherId, imprint: sel.imprint, rrp: sel.rrp,
      source: "bookclub", sourceLabel: `Book Club — ${club.name}`, sourceLink: sel.id,
      account: club.location, orderType: "bookclub", state: "draft",
      draftKey: `bc-${sel.clubId}`, createdAt: sel.selectedAt, ...base,
    });
  }

  // Draft: event stock (two titles, one card).
  lines.push(
    { id: "HL-ev1", title: "The Bee Sting", isbn: "9780241347355", quantity: 40, publisherId: "pubPRH", imprint: "Hamish Hamilton", rrp: 20.0, source: "events", sourceLabel: "Event — Paul Murray in conversation", sourceLink: "ev_12", account: "Prologue", orderType: "events", state: "draft", draftKey: "ev-12", createdAt: daysAgoIso(3), ...base },
    { id: "HL-ev2", title: "Orbital", isbn: "9781529922936", quantity: 25, publisherId: "pubPRH", imprint: "Vintage", rrp: 14.99, source: "events", sourceLabel: "Event — Paul Murray in conversation", sourceLink: "ev_12", account: "Prologue", orderType: "events", state: "draft", draftKey: "ev-12", createdAt: daysAgoIso(3), ...base },
    // Draft: schools — deliberately stale (> 7 days) for the reminder flag.
    { id: "HL-sc1", title: "Wild Houses", isbn: "9780008626433", quantity: 30, publisherId: "pubHarper", imprint: "Fourth Estate", rrp: 16.99, source: "schools", sourceLabel: "School — Stockport Grammar Y10 set text", sourceLink: "sc_3", account: "Simply Books", orderType: "schools", state: "draft", draftKey: "sc-3", createdAt: daysAgoIso(10), ...base },
    // Draft: customer special order — no account assigned yet (push blocked).
    { id: "HL-co1", title: "Held", isbn: "9781526666246", quantity: 2, publisherId: "pubBloomsbury", imprint: "Bloomsbury Circus", rrp: 18.99, source: "customer", sourceLabel: "Customer order — R. Barnes (special order)", sourceLink: "ordA6", account: null, orderType: "restock", state: "draft", draftKey: "co-ordA6", createdAt: daysAgoIso(1), ...base },

    // Pending queue — spread across publisher × account so batches form and
    // sources visibly merge (C3).
    { id: "HL-p1", title: "Intermezzo", isbn: "9780571391110", quantity: 12, publisherId: "pubFaber", imprint: "Faber", rrp: 20.0, source: "bookclub", sourceLabel: "Book Club — First Chapter Club", sourceLink: "", account: "Prologue", orderType: "bookclub", state: "pending", draftKey: null, createdAt: daysAgoIso(8), ...base },
    { id: "HL-p2", title: "Caledonian Road", isbn: "9781399813204", quantity: 18, publisherId: "pubFaber", imprint: "Faber", rrp: 20.0, source: "events", sourceLabel: "Event — Andrew O'Hagan", sourceLink: "ev_9", account: "Prologue", orderType: "events", state: "pending", draftKey: null, createdAt: daysAgoIso(7), ...base },
    { id: "HL-p3", title: "James", isbn: "9781035031245", quantity: 14, publisherId: "pubPanMac", imprint: "Mantle", rrp: 18.99, source: "bookclub", sourceLabel: "Book Club — Bramhall Readers", sourceLink: "", account: "Simply Books", orderType: "bookclub", state: "pending", draftKey: null, createdAt: daysAgoIso(6), ...base },
    { id: "HL-p4", title: "The Ministry of Time", isbn: "9781399726368", quantity: 9, publisherId: "pubPanMac", imprint: "Picador", rrp: 16.99, source: "schools", sourceLabel: "School — St Anne's reading group", sourceLink: "sc_1", account: "Simply Books", orderType: "schools", state: "pending", draftKey: null, createdAt: daysAgoIso(6), ...base },
    { id: "HL-p5", title: "The Wren, The Wren", isbn: "9781787334298", quantity: 16, publisherId: "pubPRH", imprint: "Jonathan Cape", rrp: 18.99, source: "bookclub", sourceLabel: "Book Club — Killer Lines", sourceLink: "", account: "Prologue", orderType: "bookclub", state: "pending", draftKey: null, createdAt: daysAgoIso(5), ...base },

    // Ordered / outstanding (Flow C — what gets chased).
    { id: "HL-o1", title: "Enlightenment", isbn: "9781787334618", quantity: 20, publisherId: "pubPRH", imprint: "Jonathan Cape", rrp: 18.99, source: "events", sourceLabel: "Event — Sarah Perry", sourceLink: "ev_7", account: "Prologue", orderType: "events", state: "ordered", draftKey: null, createdAt: daysAgoIso(16), ...base, sentAt: daysAgoIso(14), sentBy: "Ben", sentMethod: "Email", sentCopy: "(seed) order email — Enlightenment ×20" },
    { id: "HL-o2", title: "Held", isbn: "9781526666246", quantity: 22, publisherId: "pubBloomsbury", imprint: "Bloomsbury Circus", rrp: 18.99, source: "bookclub", sourceLabel: "Book Club — Book & Bottle", sourceLink: "", account: "Prologue", orderType: "bookclub", state: "ordered", draftKey: null, createdAt: daysAgoIso(17), ...base, sentAt: daysAgoIso(15), sentBy: "Ben", sentMethod: "Email", sentCopy: "(seed) order email — Held ×22" },
    { id: "HL-o3", title: "The Marlow Murder Club", isbn: "9780008527915", quantity: 11, publisherId: "pubHarper", imprint: "Borough Press", rrp: 9.99, source: "bookclub", sourceLabel: "Book Club — Cosy Crime", sourceLink: "", account: "Simply Books", orderType: "bookclub", state: "ordered", draftKey: null, createdAt: daysAgoIso(22), ...base, sentAt: daysAgoIso(20), sentBy: "Lynsey", sentMethod: "CSV", sentCopy: "(seed) CSV export — Marlow Murder Club ×11" },

    // Arrived (terminal).
    { id: "HL-a1", title: "Orbital", isbn: "9781529922936", quantity: 15, publisherId: "pubPRH", imprint: "Vintage", rrp: 14.99, source: "bookclub", sourceLabel: "Book Club — Far Horizons SFF", sourceLink: "", account: "Prologue", orderType: "bookclub", state: "arrived", draftKey: null, createdAt: daysAgoIso(38), ...base, sentAt: daysAgoIso(36), sentBy: "Ben", sentMethod: "Email", sentCopy: "(seed)", arrivedAt: daysAgoIso(30) }
  );

  const restock: RestockItem[] = [
    { id: "rs1", title: "The Let Them Theory", isbn: "9781035065363", quantity: 6, location: "Prologue", by: "Sam", supplier: "Gardners", createdAt: daysAgoIso(0), handledAt: null, handledBy: "" },
    { id: "rs2", title: "Butter", isbn: "9780008658397", quantity: 4, location: "Prologue", by: "Priya", supplier: "Gardners", createdAt: daysAgoIso(0), handledAt: null, handledBy: "" },
    { id: "rs3", title: "The Examiner", isbn: "9780571390137", quantity: 3, location: "Simply Books", by: "Grace", supplier: "Penguin Random House", createdAt: daysAgoIso(1), handledAt: null, handledBy: "" },
    { id: "rs4", title: "Careless People", isbn: "9781035070404", quantity: 5, location: "Simply Books", by: "Grace", supplier: "Penguin Random House", createdAt: daysAgoIso(1), handledAt: null, handledBy: "" },
    { id: "rs5", title: "Nexus", isbn: "9781529931790", quantity: 2, location: "Prologue", by: "Owen", supplier: "Bloomsbury", createdAt: daysAgoIso(2), handledAt: null, handledBy: "" },
  ];

  return { lines, publishers: PUBLISHER_SEED.map((p) => ({ ...p, accountNumbers: { ...p.accountNumbers }, rates: { ...p.rates }, accountOverrides: JSON.parse(JSON.stringify(p.accountOverrides)) })), restock };
}

const g = globalThis as typeof globalThis & { __hubStore?: Store };
const store = (): Store => (g.__hubStore ??= seed());

const entry = (by: string, action: string): AuditEntry => ({ at: new Date().toISOString(), by, action });

let idN = 500;

function newLine(input: HubLineInput, byName: string, draftKey: string): HubLine {
  return {
    ...input,
    id: `HL${++idN}`,
    state: "draft",
    draftKey,
    createdAt: new Date().toISOString(),
    receivedQuantity: 0, sentAt: null, sentBy: "", sentMethod: "", sentCopy: "", arrivedAt: null,
    log: [entry(byName, "Staged as draft")],
  };
}

export const mockHubDataSource: HubDataSource = {
  async listLines() {
    return store().lines;
  },
  async getLine(id) {
    return store().lines.find((l) => l.id === id) ?? null;
  },

  async createDraft(inputs, byName) {
    const draftKey = `d${Date.now().toString(36)}${++idN}`;
    const created = inputs.map((i) => newLine(i, byName, i.draftKey ?? draftKey));
    store().lines.push(...created);
    return created;
  },
  async upsertSourceDraft(input, byName) {
    const s = store();
    const existing = s.lines.find(
      (l) => l.source === input.source && l.sourceLink === input.sourceLink && l.state === "draft"
    );
    if (existing) {
      Object.assign(existing, {
        title: input.title, isbn: input.isbn, quantity: input.quantity,
        publisherId: input.publisherId, imprint: input.imprint, rrp: input.rrp,
        account: input.account,
      });
      existing.log.push(entry(byName, "Draft updated from source"));
      return existing;
    }
    const line = newLine(input, byName, input.draftKey ?? `d${Date.now().toString(36)}${++idN}`);
    s.lines.push(line);
    return line;
  },
  async updateDraftLine(id, patch) {
    const l = store().lines.find((x) => x.id === id);
    if (!l || l.state !== "draft") throw new Error("Draft line not found");
    if (patch.quantity != null) patch.quantity = Math.max(0, Math.floor(patch.quantity));
    Object.assign(l, patch);
    return l;
  },
  async setDraftAccount(draftKey, account, byName) {
    for (const l of store().lines) {
      if (l.draftKey === draftKey && l.state === "draft") {
        l.account = account;
        l.log.push(entry(byName, `Assigned to ${account}`));
      }
    }
  },
  async deleteDraft(draftKey, byName) {
    const s = store();
    const removed = s.lines.filter((l) => l.draftKey === draftKey && l.state === "draft");
    // Logged delete (C2) — the log lives on the removed lines; keep a tomb
    // entry out of scope for mock (Airtable impl archives instead).
    void byName;
    s.lines = s.lines.filter((l) => !(l.draftKey === draftKey && l.state === "draft"));
    return removed;
  },
  async pushDraft(draftKey, byName) {
    const s = store();
    const lines = s.lines.filter((l) => l.draftKey === draftKey && l.state === "draft");
    if (lines.length === 0) throw new Error("Draft not found");
    if (lines.some((l) => !l.account)) throw new Error("Assign an account before pushing");
    for (const l of lines) {
      l.state = "pending";
      l.log.push(entry(byName, "Pushed to hub (pending)"));
    }
    return lines;
  },

  async markSent(publisherId, account, method, byName, sentCopy) {
    const now = new Date().toISOString();
    const lines = store().lines.filter(
      (l) => l.state === "pending" && l.publisherId === publisherId && l.account === account
    );
    for (const l of lines) {
      l.state = "ordered";
      l.sentAt = now;
      l.sentBy = byName;
      l.sentMethod = method;
      l.sentCopy = sentCopy;
      l.log.push(entry(byName, `Sent via ${method}`));
    }
    return lines;
  },

  async markArrived(lineIds, byName) {
    return this.receive(lineIds.map((lineId) => ({ lineId, quantity: Number.MAX_SAFE_INTEGER })), byName);
  },

  async receive(receipts, byName) {
    const now = new Date().toISOString();
    const lines: HubLine[] = [];
    for (const receipt of receipts) {
      const l = store().lines.find((line) => line.id === receipt.lineId && line.state === "ordered");
      if (!l) continue;
      l.receivedQuantity = Math.min(l.quantity, l.receivedQuantity + Math.max(1, Math.floor(receipt.quantity)));
      if (l.receivedQuantity >= l.quantity) {
        l.state = "arrived";
        l.arrivedAt = now;
        l.log.push(entry(byName, `Delivery complete (${l.receivedQuantity}/${l.quantity})`));
      } else {
        l.log.push(entry(byName, `Partial delivery (${l.receivedQuantity}/${l.quantity})`));
      }
      lines.push(l);
    }
    return lines;
  },

  async listPublishers() {
    return store().publishers;
  },
  async createPublisher(input: HubPublisherInput) {
    const p: HubPublisher = { id: `pub${++idN}`, ...input };
    store().publishers.push(p);
    return p;
  },
  async updatePublisher(id, input) {
    const p = store().publishers.find((x) => x.id === id);
    if (!p) throw new Error("Publisher not found");
    Object.assign(p, input);
    return p;
  },

  async listRestock() {
    return store().restock;
  },
  async addRestock(input: RestockItemInput) {
    const r: RestockItem = { id: `rs${++idN}`, ...input, createdAt: new Date().toISOString(), handledAt: null, handledBy: "" };
    store().restock.unshift(r);
    return r;
  },
  async handleRestock(id, byName) {
    const r = store().restock.find((x) => x.id === id);
    if (!r) throw new Error("Restock item not found");
    r.handledAt = new Date().toISOString();
    r.handledBy = byName;
    return r;
  },
};
